"""
Lola Meeting Ops — Attio sync.

Pushes structured meeting notes into Attio as a note on
relevant people records. Uses append-safe behavior.
Never overwrites existing CRM data.
"""

from __future__ import annotations

import logging
from typing import Optional

from .config import MeetingOpsConfig
from .models import StructuredMeetingNote

logger = logging.getLogger("lola.meeting_ops.attio_sync")


def _format_note_body(note: StructuredMeetingNote) -> str:
    """Format structured note as markdown for Attio note body."""
    lines = [
        f"# Meeting: {note.subject}",
        f"**Date:** {note.start_time.strftime('%Y-%m-%d %H:%M UTC')}",
        f"**Organizer:** {note.organizer}",
        f"**Source confidence:** {note.source_confidence}",
        "",
    ]

    if note.executive_summary:
        lines += ["## Summary", note.executive_summary, ""]

    if note.topics:
        lines += ["## Topics Discussed"] + [f"- {t}" for t in note.topics] + [""]

    if note.decisions:
        lines += ["## Decisions"] + [f"- {d}" for d in note.decisions] + [""]

    if note.action_items:
        lines += ["## Action Items"]
        for ai in note.action_items:
            due = f" (due: {ai.due_date})" if ai.due_date else ""
            lines.append(f"- **{ai.owner}**: {ai.task}{due}")
        lines.append("")

    if note.open_questions:
        lines += ["## Open Questions"] + [f"- {q}" for q in note.open_questions] + [""]

    if note.commitments_risks:
        lines += ["## Commitments / Risks"] + [f"- {c}" for c in note.commitments_risks] + [""]

    lines.append(f"_Generated by Lola meeting-ops. Artifacts: {', '.join(note.raw_artifact_refs) or 'none'}_")
    return "\n".join(lines)


async def sync_to_attio(
    note: StructuredMeetingNote,
    external_attendee_emails: list[str],
    cfg: MeetingOpsConfig,
) -> bool:
    """
    Create a note in Attio for each external attendee found in the CRM.
    Returns True if at least one note was created.
    """
    if not cfg.attio_api_key:
        logger.warning("ATTIO_API_KEY not set — skipping Attio sync")
        return False

    try:
        import sys, os
        src = os.path.join(os.path.dirname(__file__), "..", "..", "..", "..", "src")
        if src not in sys.path:
            sys.path.insert(0, src)
        from openclaw.integrations.attio.client import AttioClient
    except ImportError:
        logger.error("Attio client not importable — skipping sync")
        return False

    note_title = f"Meeting Notes: {note.subject} ({note.start_time.strftime('%Y-%m-%d')})"
    note_body = _format_note_body(note)
    created = 0

    try:
        c = AttioClient(api_key=cfg.attio_api_key)

        for email in external_attendee_emails:
            if not email:
                continue
            try:
                # Find person record by email
                results = await c.search_records("people", email, limit=3)
                matched = None
                for r in results:
                    attrs = r.get("values", {})
                    for e_entry in attrs.get("email_addresses", []):
                        if e_entry.get("email_address", "").lower() == email.lower():
                            matched = r
                            break
                    if matched:
                        break

                if not matched:
                    logger.info("No Attio person record found for %s — skipping", email)
                    continue

                record_id = matched.get("id", {}).get("record_id", "")
                if not record_id:
                    continue

                # Create note on the record
                await c._post("/notes", {
                    "data": {
                        "parent_object": "people",
                        "parent_record_id": record_id,
                        "title": note_title,
                        "content": {
                            "document": {
                                "schema": "2",
                                "content": [
                                    {
                                        "type": "paragraph",
                                        "content": [{"type": "text", "text": note_body}],
                                    }
                                ],
                            }
                        },
                    }
                })
                logger.info("Attio note created for person %s meeting=%s", email, note.meeting_id)
                created += 1

            except Exception as e:
                logger.warning("Attio note creation failed for %s: %s", email, e)

        await c.close()

    except Exception as e:
        logger.error("Attio sync outer error: %s", e)
        return False

    logger.info("Attio sync complete meeting=%s notes_created=%d", note.meeting_id, created)
    return created > 0
